{
 "title": "SB3x_Netty_Grafana_dashboard",
 "description": "SB3x_Netty_Grafana_dashboard",
 "time": { "from": "now-15m", "to": "now" },
 "refresh": "5s",
 "panels": [
  { "title": "Application", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "http_server_requests_seconds_sum",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 9, "x": 0, "y": 1 },
   "targets": [
    {
     "expr": "http_server_requests_seconds_sum",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "http_server_requests_active_seconds_count",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 6, "x": 9, "y": 1 },
   "targets": [
    {
     "expr": "http_server_requests_active_seconds_count",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "container_oom_events_total",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 4, "x": 15, "y": 1 },
   "targets": [
    { "expr": "container_oom_events_total", "legendFormat": "{{container_label_app}}" }
   ]
  },
  {
   "title": "reactor_netty_eventloop_pending_tasks",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 5, "x": 19, "y": 1 },
   "targets": [
    {
     "expr": "reactor_netty_eventloop_pending_tasks",
     "legendFormat": "{{instance}}-{{name}}"
    }
   ]
  },
  { "title": "Memory", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 8 } },
  {
   "title": "node_pressure_memory_waiting_seconds_total",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 6, "x": 0, "y": 9 },
   "targets": [
    {
     "expr": "node_pressure_memory_waiting_seconds_total",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "jvm_memory_used_bytes",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 7, "x": 6, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    { "expr": "jvm_memory_used_bytes", "legendFormat": "{{instance}}-{{area}}" }
   ]
  },
  {
   "title": "container_memory_usage_bytes",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 6, "x": 13, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "bits" } },
   "targets": [
    { "expr": "container_memory_usage_bytes", "legendFormat": "{{container_label_app}}" }
   ]
  },
  {
   "title": "container_spec_memory_limit_bytes",
   "type": "stat",
   "gridPos": { "h": 7, "w": 5, "x": 19, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "bits" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "avg(container_spec_memory_limit_bytes)",
     "legendFormat": "__auto"
    }
   ]
  },
  { "title": "CPU", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 16 } },
  {
   "title": "node_cpu_core_throttles_total",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 7, "x": 0, "y": 17 },
   "targets": [
    { "expr": "node_cpu_core_throttles_total", "legendFormat": "{{instance}}" }
   ]
  },
  {
   "title": "node_pressure_cpu_waiting_seconds_total",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 7, "x": 7, "y": 17 },
   "targets": [
    {
     "expr": "node_pressure_cpu_waiting_seconds_total",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "container_cpu_cfs_throttled_seconds_total",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 5, "x": 14, "y": 17 },
   "targets": [
    {
     "expr": "container_cpu_cfs_throttled_seconds_total",
     "legendFormat": "{{container_label_io_kubernetes_container_name}}"
    }
   ]
  },
  {
   "title": "container_cpu_usage_seconds_total",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 5, "x": 19, "y": 17 },
   "targets": [
    {
     "expr": "container_cpu_usage_seconds_total",
     "legendFormat": "{{container_label_app}}-{{container_label_io_kubernetes_pod_name}}"
    }
   ]
  },
  {
   "title": "process_cpu_usage",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 24 },
   "targets": [
    { "expr": "process_cpu_usage", "legendFormat": "{{instance}}" }
   ]
  },
  {
   "title": "system_cpu_usage",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 24 },
   "targets": [
    { "expr": "system_cpu_usage", "legendFormat": "{{instance}}" }
   ]
  }
 ]
}