apiVersion: v1
kind: ServiceAccount
metadata:
  name: atlantis
  namespace: atlantis
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: atlantis
rules:
- apiGroups: ["*"]
  resources: ["*"]
  verbs: ["*"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: atlantis
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: atlantis
subjects:
- kind: ServiceAccount
  name: atlantis
  namespace: atlantis
