apiVersion: v1
kind: Service
metadata:
  name: atlantis
  namespace: atlantis
spec:
  type: NodePort
  selector:
    app: atlantis
  ports:
  - name: http
    port: 4141
    targetPort: 4141
    nodePort: 30141
