apiVersion: v1
kind: Service
metadata:
  name: cadvisor-service
  labels:
    app: cadvisor
spec:
  selector:
    app: cadvisor
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 8080
  type: ClusterIP