apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: cadvisor
spec:
  selector:
    matchLabels:
      app: cadvisor
  template:
    metadata:
      labels:
        app: cadvisor
    spec:
      automountServiceAccountToken: false
      containers:
        - name: cadvisor
          image: gcr.io/cadvisor/cadvisor:v0.46.0
          imagePullPolicy: IfNotPresent
          args:
            - --logtostderr
            - --v=4
          ports:
            - containerPort: 8080
              name: metrics
          volumeMounts:
            - name: sys
              mountPath: /sys
              readOnly: true
            - name: var-run
              mountPath: /var/run
              readOnly: true
            - name: docker
              mountPath: /var/lib/docker
              readOnly: true
            - name: cgroup
              mountPath: /sys/fs/cgroup
              readOnly: true
            - name: dev-disk
              mountPath: /dev/disk
              readOnly: true
            - name: proc
              mountPath: /proc
              readOnly: true
      volumes:
        - name: sys
          hostPath:
            path: /sys
        - name: var-run
          hostPath:
            path: /var/run
        - name: docker
          hostPath:
            path: /var/lib/docker
        - name: cgroup
          hostPath:
            path: /sys/fs/cgroup
        - name: dev-disk
          hostPath:
            path: /dev/disk
        - name: proc
          hostPath:
            path: /proc