apiVersion: apps/v1
kind: Deployment
metadata:
  name: spring-boot-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: spring-boot-app
  template:
    metadata:
      labels:
        app: spring-boot-app
    spec:
      containers:
        - name: spring-boot-app
          image: app:latest
          imagePullPolicy: IfNotPresent # to avoid pulling the image from the registry
          ports:
            - containerPort: 8080
          env:
            - name: TAG
              value: "spring-boot-webflux-3x"
          resources:
            limits:
              memory: "4096Mi"
              cpu: "4095m"
            requests:
              memory: "4096Mi"
              cpu: "4095m"