apiVersion: v1
kind: ConfigMap
metadata:
  name: prometheus-config-ne
data:
  prometheus.yml: |
    global:
      scrape_interval: 2s
    scrape_configs:
      - job_name: 'node-exporter'
        metrics_path: /metrics
        static_configs:
          - targets: ['node-exporter-service:9100']