apiVersion: v1
kind: ConfigMap
metadata:
  name: prometheus-config
data:
  prometheus.yml: |
    global:
      scrape_interval: 2s
    scrape_configs:
      - job_name: 'sb3-netty-app'
        metrics_path: '/actuator/prometheus'
        static_configs:
          - targets: ['sb3-netty-service:8080']
      - job_name: 'node-exporter'
        metrics_path: /metrics
        static_configs:
          - targets: ['node-exporter-service:9100']