apiVersion: apps/v1
kind: Deployment
metadata:
  name: sb3-netty-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: sb3-netty-app
  template:
    metadata:
      labels:
        app: sb3-netty-app
    spec:
      containers:
        - name: sb3-netty-app
          image: sb3-netty:latest
          imagePullPolicy: IfNotPresent # to avoid pulling the image from the registry
          ports:
            - containerPort: 8080
          env:
            - name: TAG
              value: "sb3-netty-app"
          resources:
            limits:
              memory: "4096Mi"
              cpu: "4095m"
            requests:
              memory: "4096Mi"
              cpu: "4095m"