apiVersion: apps/v1
kind: Deployment
metadata:
  name: trivy-server
  namespace: harbor
spec:
  replicas: 1
  selector:
    matchLabels:
      app: trivy-server
  template:
    metadata:
      labels:
        app: trivy-server
    spec:
      containers:
      - name: trivy
        image: aquasec/trivy:latest
        args:
        - server
        - --listen
        - 0.0.0.0:8080
        ports:
        - containerPort: 8080
        resources:
          requests:
            memory: 512Mi
            cpu: 200m
          limits:
            memory: 1Gi
            cpu: 1000m
---
apiVersion: v1
kind: Service
metadata:
  name: trivy-server
  namespace: harbor
spec:
  type: ClusterIP
  selector:
    app: trivy-server
  ports:
  - port: 8080
    targetPort: 8080
