FROM apache/airflow:2.10.4
USER airflow
RUN pip3 install openlineage-python
RUN pip3 install openlineage-airflow
RUN pip3 install apache-airflow-providers-postgres
RUN pip3 install apache-airflow-providers-openlineage 