services:
  postgres:
    image: postgres:13
    container_name: postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: postgres
    volumes:
      - ./init-users.sql:/docker-entrypoint-initdb.d/01-init-users.sql
      - ./init-databases.sql:/docker-entrypoint-initdb.d/02-init-databases.sql
      - postgres-data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 10s
      timeout: 5s
      retries: 5

  marquez:
    image: marquezproject/marquez:latest
    container_name: marquez
    environment:
      MARQUEZ_DB_HOST: postgres
      MARQUEZ_DB_PORT: 5432
      MARQUEZ_DB_USER: marquez
      MARQUEZ_DB_PASSWORD: marquez
      MARQUEZ_DB_NAME: marquez_db
      MARQUEZ_PORT: 5000
    depends_on:
      postgres:
        condition: service_healthy
    ports:
      - "5000:5000"

  airflow:
    #image: apache/airflow:2.10.4
    build:
      context: .
      dockerfile: Dockerfile.airflow
    container_name: airflow
    environment:
      AIRFLOW__CORE__EXECUTOR: LocalExecutor
      AIRFLOW__DATABASE__SQL_ALCHEMY_CONN: postgresql://airflow:airflow@postgres:5432/airflow
      AIRFLOW_CONN_POSTGRES_DEFAULT: postgresql://airflow:airflow@postgres:5432/airflow
      AIRFLOW__OPENLINEAGE__TRANSPORT: '{"type": "http", "url": "http://marquez:5000", "endpoint": "api/v1/lineage"}'
      AIRFLOW__OPENLINEAGE__NAMESPACE: "my-team-airflow-instance"
    volumes:
      - ./dags:/opt/airflow/dags
      - airflow-logs:/opt/airflow/logs
      - airflow-plugins:/opt/airflow/plugins
    depends_on:
      postgres:
        condition: service_healthy
      marquez:
        condition: service_started
    ports:
      - "8080:8080"
    command: ["bash", "-c", "airflow db migrate && airflow webserver & airflow scheduler"]
    restart: always
    healthcheck:
      test: ["CMD", "airflow", "db", "check"]
      interval: 30s
      timeout: 10s
      retries: 5
      start_period: 30s

volumes:
  postgres-data:
  airflow-logs:
  airflow-plugins: