FROM node:24-bookworm-slim
USER node
WORKDIR /app
COPY --chown=node:node package.json package-lock.json ./
RUN npm ci --omit=dev
COPY --chown=node:node public ./public
COPY --chown=node:node src ./src
COPY --chown=node:node test ./test
EXPOSE 3000
CMD ["node", "src/server.js"]
