apiVersion: v1
kind: ConfigMap
metadata:
  name: flink-config
  namespace: flink-sedona
data:
  flink-conf.yaml: |
    jobmanager.rpc.address: flink-jobmanager
    jobmanager.memory.process.size: 1600m
    taskmanager.numberOfTaskSlots: 4
    taskmanager.memory.process.size: 1728m
    taskmanager.memory.flink.size: 1280m
    parallelism.default: 2
    taskmanager.registration.timeout: 5min
    taskmanager.rpc.bind-policy: ip
  log4j-console.properties: |
    rootLogger.level = INFO
    rootLogger.appenderRef.console.ref = ConsoleAppender
    appender.console.name = ConsoleAppender
    appender.console.type = CONSOLE
    appender.console.layout.type = PatternLayout
    appender.console.layout.pattern = %d{yyyy-MM-dd HH:mm:ss,SSS} %-5p %-60c %x - %m%n
