version: '3.8'
services:
  mysql:
    image: 'mysql:latest'
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: db
    ports:
      - "3306:3306"
    volumes:
      - mysql-data:/var/lib/mysql

  liquibase:
    image: liquibase/liquibase
    volumes:
      - ./changelog:/liquibase/changelog
      - ./scripts:/liquibase/changelog
      - ./driver:/liquibase/lib
    depends_on:
      - mysql
    command: ["--classpath=/liquibase/lib/mysql-connector-j-9.0.0.jar", "--defaultsFile=/liquibase/changelog/liquibase.properties", "update"]

volumes:
  mysql-data: {}