version: '3.8'
services:
  mysql:
    image: 'mysql:latest'
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: db
    ports:
      - "3306:3306"
    volumes:
      - mysql-data:/var/lib/mysql
    healthcheck:
      test: ["CMD", "mysqladmin" ,"ping", "-h", "localhost"]
      interval: 10s
      timeout: 5s
      retries: 5      

  liquibase:
    image: liquibase/liquibase
    volumes:
      - ./scripts:/liquibase/changelog/
      - ./driver:/liquibase/lib/
    depends_on:
      - mysql
    command: ["--classpath=/liquibase/lib/mysql-connector-j-9.0.0.jar", 
              "--defaultsFile=/liquibase/changelog/liquibase.properties", 
              "--searchPath=/liquibase/changelog/",
              "--changeLogFile=/liquibase/changelog/changelog-master.xml", 
              "update"]

volumes:
  mysql-data: {}