version: '3.8'
services:
  mysql:
    image: 'mysql:latest'
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_DATABASE: db
      MYSQL_USER: root
      MYSQL_PASSWORD: root
    ports:
      - "3306:3306"
    volumes:
      - mysql-data:/var/lib/mysql

  liquibase:
    image: liquibase/liquibase
    volumes:
      - ./scripts:/liquibase/changelog
    depends_on:
      - mysql
    environment:
      LIQUIBASE_URL: jdbc:mysql://mysql/db
      LIQUIBASE_USERNAME: root
      LIQUIBASE_PASSWORD: root
      LIQUIBASE_CHANGELOG: /liquibase/changelog/changelog-master.xml
    command: ["update"]

volumes:
  mysql-data: {}