version: '3.8'
services:
  mysql:
    image: 'mysql:latest'
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: db
    ports:
      - "3306:3306"
    volumes:
      - mysql-data:/var/lib/mysql

  liquibase:
    image: liquibase/liquibase
    volumes:
      - ./scripts:/liquibase/changelog
    depends_on:
      - mysql
    command: ["--defaultsFile=/liquibase/changelog/liquibase.properties", "update"]

volumes:
  mysql-data: {}