version: '3.8'
services:
  mysql:
    image: 'mysql:latest'
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: db
    ports:
      - "3306:3306"
    volumes:
      - mysql-data:/var/lib/mysql
    healthcheck:
      test: ["CMD", "mysqladmin" ,"ping", "-h", "localhost"]
      interval: 10s
      timeout: 5s
      retries: 5      

  liquibase:
    image: liquibase/liquibase
    volumes:
      - ./changelog:/liquibase/
      - ./scripts:/liquibase/
      - ./driver:/liquibase/
    depends_on:
      - mysql
    command: ["--classpath=/liquibase/mysql-connector-j-9.0.0.jar", "--defaultsFile=/liquibase/liquibase.properties", "--changeLogFile=/liquibase/changelog-master.xml", "update"]

volumes:
  mysql-data: {}