apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.app.name }}
spec:
  selector:
    app: {{ .Values.app.name }}
  ports:
  - port: {{ .Values.app.port }}
    targetPort: {{ .Values.app.port }}
    nodePort: 30080
  type: NodePort
