apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: webappgo
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: webappgo
        tier: frontend
    spec:
      containers:
      - name: webappgo
        image: webappgo:v1
        resources:
          requests:
            cpu: 100m
            memory: 100Mi
        env:
        - name: REDIS_URL
          value: redis.default.svc.cluster.local:6379
        - name: GET_HOSTS_FROM
          value: dns
        ports:
        - containerPort: 9090
