apiVersion: v1
kind: Service
metadata:
  name: webappgo
  labels:
    app: webappgo
    tier: frontend
spec:
  type: LoadBalancer
  ports:
  - port: 9090
  selector:
    app: webappgo
    tier: frontend
