apiVersion: apps/v1
kind: Deployment
metadata:
  name: rust-webservice
  namespace: default
spec:
  replicas: 1
  selector:
    matchLabels:
      app: rust-webservice
  template:
    metadata:
      labels:
        app: rust-webservice
    spec:
      containers:
      - name: rust-webservice
        image: localhost/rust-webservice:latest
        imagePullPolicy: Never
        ports:
        - containerPort: 8080
        resources:
          requests:
            cpu: 50m
            memory: 128Mi
          limits:
            cpu: 100m
            memory: 256Mi
        livenessProbe:
          httpGet:
            path: /health
            port: 8080
          initialDelaySeconds: 5
          periodSeconds: 10
        readinessProbe:
          httpGet:
            path: /health
            port: 8080
          initialDelaySeconds: 5
          periodSeconds: 5
